### ISSUE TITLE
amd-10.js contains a faulty IIFE

### ISSUE THREAD

**Issue by jrauschenbusch** [guybedford/system-register-dynamic-amd-cases#1]
I think there's a copy paste error in this line:
https://github.com/guybedford/system-register-dynamic-amd-cases/blob/master/expectations/amd-11.js#L18

Is the array expression really wanted in the IIFE? Or should it look like the following?

``` javascript
System.registerDynamic(['amd-10.js'], false, function($__require, $__exports, $__module) {
  return (function(m) {
    return m;
  }).call(this, $__require('amd-10.js'));
});
```

**Comment by guybedford** [comment]
Thanks, yes this is correct! I've added the change.
